e_fm: fix last commit to compile again with clang
Commit fd8d41a2a6f1dc374932f18e69daf485c1cb5a3e introduced a void return in a
non void function. On gcc this only produced a warnigns but it was a hard
error on clang and should be fixed.

00:25:24.906 src/bin/e_fm.c:1523:15: error: non-void function 'e_fm2_icon_file_get' should return a
value [-Wreturn-type]
00:25:24.950    if (!file) return;