remove access module from build
this hasn't been updated in over 1.5 years and has caused me to waste time repeatedly fixing build-related issues. in addition, it uses symbols which are no longer even available in efl.

if nobody updates/maintains this, it will be removed for e20 release

src/modules/access/e_mod_main.c: In function '_cover_new':
src/modules/access/e_mod_main.c:765:4: warning: implicit declaration of function 'ecore_x_input_multi_select' [-Wimplicit-function-declaration]